const Movie = require("../models/movie");
const Studio = require("../models/studio");

const router = require("express").Router();

// get all studios
router.get("/", async(req, res) => {
    try {
        const studios = await Studio.findAll();
        res.status(200).json({studios: studios});
    } catch (err) {
        res.status(500).json({message: "server error", err: err})
    }
});

// create a studio
router.post("/", async(req, res) => {
    try {
        const newStudio = await Studio.create(req.body);
        res.status(200).json({studio: newStudio});
    } catch (err) {
        res.status(500).json({message: "server error", err: err})
    }
});

// add a movie to a studio
router.post("/:studioId/movies", async(req, res) => {
    try {
        const studio = await Studio.findByPk(req.params.studioId);
        if (studio) {
            const movie = new Movie(req.body);
            movie.studioId = studio.id;
            await movie.save();
            res.status(201).json({message:"movie added to the studio", movie: movie});
        } else {
            res.status(404).json({message: "studio not found"})
        }
    } catch(err) {
        res.status(500).json({message: "server error", err: err})
    }
});

// get all movies for a studio
router.get("/:studioId/movies", async(req, res) => {
    try {
        const studio = await Studio.findByPk(req.params.studioId, {
            include: [Movie]
        });
        if (studio) {
            res.status(200).json({movies: studio.movies})
        } else {
            res.status(404).json({message:"studio not found."})
        }
    } catch (err) {
        res.status(500).json({message: "server error", err: err})
    }
})

// update a movie that belongs to a studio
router.put("/:studioId/movies/:movieId", async(req, res) => {
    try {
        const studio = await Studio.findByPk(req.params.studioId);
        if (studio) {
            // getMovies is a function that's generated by sequelize
            const movies = await studio.getMovies({id: req.params.movieId});
            // movies should be an array with only one element (the movie we're looking for)
            const movie = movies[0];
            if (movie) {
                const updatedMovie = await movie.update(req.body);
                res.status(202).json({message: "changes accepted", movie: updatedMovie});
            } else {
                res.status(404).json({message:"movie not found."})
            }
        } else {
            res.status(404).json({message:"studio not found."})
        }
    } catch (err) {
        res.status(500).json({message: "server error", err: err})
    }
})

// delete a movie from a studio
router.delete("/:studioId/movies/:movieId", async(req, res) => {
    try {
        const studio = await Studio.findByPk(req.params.studioId);
        if (studio) {
            // getMovies is a function that's generated by sequelize
            const movies = await studio.getMovies({id: req.params.movieId});
            // movies should be an array with only one element (the movie we're looking for)
            const movie = movies[0];
            if (movie) {
                await movie.destroy();
                res.status(200).json({message: "deleted movie", movie: movie});
            } else {
                res.status(404).json({message:"movie not found."})
            }
        } else {
            res.status(404).json({message:"studio not found."})
        }
    } catch (err) {
        res.status(500).json({message: "server error", err: err})
    }
})

module.exports = router;